[package]
name = "umm"
version = "0.0.1"
edition = "2021"
authors = ["Dhruv Dhamani <ddhamani@uncc.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
clap = "2.33.3"
colored = "2.0.0"
which = "4.2.2"
inquire = "0.2.1"
ureq = "2.2.0"
glob = "0.3.0"
lazy_static = "1.4.0"
java_dependency_analyzer = { path = "../java_dependency_analyzer" }
# TODO: Change this after the release of tree-sitter-java
tree-sitter-java = { git = "https://github.com/Luni-4/tree-sitter-java.git", branch = "update-0.20" }
tree-sitter = "0.20.0"
