[package]
name = "umm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
fncmd = "1.2.4"
glob = "0.3.0"
lazy_static = "1.4.0"
tree-sitter = "0.20.4"
which = "4.2.4"
tree-sitter-java = { git = "https://github.com/Luni-4/tree-sitter-java.git", branch = "update-0.20" }
java_dependency_analyzer = { git = "https://github.com/DhruvDh/java_dependency_analyzer.git", branch = "main" }
colored = "2.0.0"

# [[bin]]
# name = "umm"
# path = "src/bin/umm.rs"
# [[bin]]
# name = "umm-check"
# path = "src/bin/umm-check.rs"
# [[bin]]
# name = "umm-run"
# path = "src/bin/umm-run.rs"
# [[bin]]
# name = "umm-test"
# path = "src/bin/umm-test.rs"
# [[bin]]
# name = "umm-clean"
# path = "src/bin/umm-clean.rs"
