cargo-features = ["profile-rustflags"]

[workspace]
members = ["umm_derive"]

[package]
name = "umm"
version = "0.2.0"
edition = "2021"
default-run = "umm"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
umm_derive = { path = "./umm_derive" }
anyhow = "1.0.53"
lazy_static = "1.4.0"
which = "4.2.4"
bpaf = { version = "0.7.0", features = ["bright-color"] }
glob = "0.3.0"
peg = "0.8.0"
tree-sitter = "0.20.4"
tree-sitter-java = { git = "https://github.com/tree-sitter/tree-sitter-java.git", rev = "39a11c8330d0b2ad75310456c378396785f79a4e" }
colored = "2.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tabled = "0.5.0"
rhai = { version = "1.10.0", features = ["metadata", "decimal", "sync"] }
self_update = { version = "0.32.0", features = ["rustls"] }
typed-builder = "0.11.0"
postgrest = "1.3.1"
reqwest = { version = "0.11.11", features = ["json"] }
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.24"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
walkdir = "2.3.2"

[profile.release]
lto = "fat"
codegen-units = 1
