[package]
name = "umm"
version = "0.1.0"
edition = "2021"
default-run = "umm"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
glob = "0.3.0"
lazy_static = "1.4.0"
tree-sitter = "0.20.4"
which = "4.2.4"
tree-sitter-java = { git = "https://github.com/Luni-4/tree-sitter-java.git", branch = "update-0.20" }
colored = "2.0.0"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
tabled = "0.5.0"
peg = "0.8.0"
ureq = "2.4.0"
# reedline = { version = "0.3.0", features = ["clipboard", "system_clipboard"] }
reedline = { git = "https://github.com/DhruvDh/reedline", features = [
    "clipboard",
    "system_clipboard",
] }
nu-ansi-term = "0.45.1"
crossterm = "0.23.2"
bpaf = "0.4.3"

# [[bin]]
# name = "umm"
# path = "src/bin/umm.rs"
# [[bin]]
# name = "umm-check"
# path = "src/bin/umm-check.rs"
# [[bin]]
# name = "umm-run"
# path = "src/bin/umm-run.rs"
# [[bin]]
# name = "umm-test"
# path = "src/bin/umm-test.rs"
# [[bin]]
# name = "umm-clean"
# path = "src/bin/umm-clean.rs"
