reorder_imports = true
imports_layout = "Vertical"
imports_granularity = "Crate"
newline_style = "Unix"
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_strings = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
struct_field_align_threshold = 20
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true
