name: Rust

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get install libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev
        rustup toolchain install nightly
        cargo +nightly build --release
        mv ./target/release/umm ./target/release/umm-x86_64-unknown-linux-gnu
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        name: main
        tag_name: summer_22
        generate_release_notes: true
        files: |
          ./target/release/umm-x86_64-unknown-linux-gnu
          
