# .github/workflows/release.yml

on:
  release:
    types: [published created edited released]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MACOSX_DEPLOYMENT_TARGET: "10.8"
        with:
          RUSTTARGET: ${{ matrix.target }}
          TOOLCHAIN_VERSION: "nightly"
          STATIC_LINKING: ${{ !contains(matrix.target, 'x86_64-apple-darwin') }}
