# .github/workflows/release.yml

on: [workflow_dispatch]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          TOOLCHAIN_VERSION: "nightly"
          UPLOAD_MODE: none
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: main
          tag_name: summer_22
          generate_release_notes: true
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
