# This is a basic workflow to help you get started with Actions

name: Crossplatform build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - target: x86_64-pc-windows-gnu
            archive: zip
            archive_name: umm-x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
            archive: zip
            archive_name: umm-x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
            archive: zip
            archive_name: umm-x86_64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOOLCHAIN_VERSION: nightly
          ARCHIVE_NAME: ${{ matrix.archive_name }}
        with:
          RUSTTARGET: ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: umm
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}      
