name: Rust

on:
  push:
    branches:
      - main
      - master
      - next
      - next-assign1-spring-22
  pull_request:
    branches:
      - main
      - master
      - next
      - next-assign1-spring-22

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo +nightly build --release --verbose
        cp ./target/release/umm-check ./umm-check
        cp ./target/release/umm-info ./umm-info
        cp ./target/release/umm-doc-check ./umm-doc-check
        cp ./target/release/umm-grade ./umm-grade
        cp ./target/release/umm-clean ./umm-clean
        cp ./target/release/umm-run ./umm-run
        cp ./target/release/umm-test ./umm-test
