name: Rust

on:
  push:
    branches:
      - main
      - master
      - next
      - next-assign1-spring-22
      - next-lab3-spring-22
      - next-assign2-spring-22
      - next-assign3-spring-22

  pull_request:
    branches:
      - main
      - master
      - next
      - next-assign1-spring-22
      - next-lab3-spring-22
      - next-assign2-spring-22
      - next-assign3-spring-22

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup toolchain install nightly
        cargo +nightly build --release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: release ${{ github.ref }}
        tag_name: prerelease-assign2
        generate_release_notes: true
        files: |
          ./target/release/umm-info
          ./target/release/umm-clean
          ./target/release/umm-check
          ./target/release/umm-doc-check
          ./target/release/umm-run
          ./target/release/umm-test
          ./target/release/umm-grade
          
