# This is a basic workflow to help you get started with Actions

name: Crossplatform build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - target: x86_64-pc-windows-gnu
            archive: zip
            archive_name: umm-x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
            archive: zip
            archive_name: umm-x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
            archive: zip
            archive_name: umm-x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get install libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@master
      - name: compile
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOOLCHAIN_VERSION: nightly
          ARCHIVE_NAME: ${{ matrix.archive_name }}
        with:
          RUSTTARGET: ${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: main
          tag_name: summer_22
          generate_release_notes: true
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }} 
            
